name1: sample-github-actions

on: push

jobs:
  sample-github-action-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
